### ISSUE TITLE
Feature request: autogrouping scenario steps

### ISSUE THREAD

**Issue by imrekoszo** [Suremaker/LightBDD#6]
At present I am aware of 2 ways of running scenarios:

### 1
```
Runner.RunScenario(
    Given_a_customer,
    And_a_product,
    When_the_customer_selects_the_product,
    Then_foo,
    Then_bar);
```

- Good: most method names state whether they are arrange, act or assert making reuse unambiguous
- Bad: And_a_product() is ambiguous (could belong to G W or T)
- Bad: Then_foo and Then_bar will be printed in the report as "Then foo Then bar" instead of "Then foo And bar" which would read better

### 2
```
Runner.RunScenario(
    given => a_customer(),
    and => a_product(),
    when => the_customer_selects_the_product(),
    then => foo(),
    and => bar());
```

- Good: whole scenario prints in a nice to read way
- Bad: all methods become simple statements with no indication whether they are arrange act or assert making reuse hard (I've seen tests where the author mistakenly reused an arrange method as an assertion because of this)

### Suggestion
Add an optional feature that formats steps in a way that if the first word of the current step equals the first word of the previous step, the first word of the current step will be replaced with And. This would result in a nicely readable output and unambiguous method names.

Example:
```
Runner.RunScenario(
    Given_a_customer,
    Given_a_product,
    When_the_customer_navigates_to_the_site,
    When_the_customer_selects_the_product,
    Then_foo,
    Then_bar);
```
would be formatted similarly to:
```
Given a customer
And a product
When the customer navigates to the site
And the customer selects the product
Then foo
And bar
```

Optional extras:
- configure case sensitivity for the comparison
- configure the number of leading words to compare and replace
- configure the replacement phrase ("And", "And also" etc.)

**Comment by Suremaker** [comment]
The next version of LightBDD would contain this change.
It would be released soon.

**Comment by Suremaker** [comment]
Done in version 1.7.0.0
