### ISSUE TITLE
Feature Request: Support for logging arbitrary text which will appear in the reports

### ISSUE THREAD

**Issue by mcgin** [Suremaker/LightBDD#7]
Right now there isn't an easy way to get my test context output to the test reports.  It would be nice if there was some option to output it easily.  Ideally I would like to specify a class that represents my test context and LightBdd includes the representation after each test run.

**Comment by Suremaker** [comment]
With a new version of LightBDD, it would be possible to comment any step during it's execution, where comments would be included on the report.

I am planning to add ```StepExecution.Comment(string comment)``` method.

It should be easily reusable for a purpose of dumping a test context, where I plan to give ability to dump it manually plus it would be dumped automatically on failing scenarios.

For automatic dumps, the test context would be:
* a test class with its fields, if Runner.RunScenario() is called without explicit context,
* a passed context with its fields, if Runner.RunScenario<MyContext> is called with MyContext context.

I have not thought through it yet, but most probably, the context dumping method would use:
* ToString() method to dump context content, or
* it will use reflection to dump all the fields by applying ToString() on them.
I will have to think how to make it customizable though...

**Comment by Suremaker** [comment]
An initial implementation is done in version 1.7.0.0.
It offers `StepExecution.Comment()` and `StepExecution.CommentFormat()` methods to manually comment steps in runtime.

The automatic context dump is not implemented in this version and it would be added in future versions if needed.
