### ISSUE TITLE
NUnit 3.0

### ISSUE THREAD

**Issue by RoyGI** [Suremaker/LightBDD#9]
Hi i cannot use NUnit 3.0 Can you upgrade it?

Regards

**Comment by Suremaker** [comment]
The NUnit 3x support has been added with LightBDD version *1.7.1*.
To use it, you will have to fetch the [LightBDD.NUnit3 package](https://www.nuget.org/packages/LightBDD.NUnit3/) from nuget.

Also, please take a look at the updated wiki page [06-Generating-Summary-File](https://github.com/Suremaker/LightBDD/wiki/06-Generating-Summary-File#summary-generation-and-nunit3-resharper-runner) as I put there a description of known issue with Resharper runner for NUnit3.

Finally, please feel free to like the project if it is useful for you ;-)
Happy coding.

**Comment by RoyGI** [comment]
Thanks
